language: java
jdk:
- oraclejdk8

deploy:
  provider: releases
  api_key:
    secure: 78a10f9847c3f3f766833f8133a0b0e0fe32c595
  file: target/EdgeConvert-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    repo: BLamy/EdgeConvert
    tags: true
