language: java
jdk:
- oraclejdk8

deploy:
  provider: releases
  api_key:
    secure: daa1b8210258a46cd6ac5ede60f48cf7521144d3
  file: target/EdgeConvert-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    repo: BLamy/EdgeConvert
    tags: true
