language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: UeZhyksSywp8Jw05ib6ppLCE6pCpNrNSK8mSayeystmtaawJ0AZjn4MpwwNa1EhFXkSVA49OjrlbEr2ZtsxWUt5Fl2ahN4iebRIzvrSDW7DVrCBU4YjqaRbQg9RI7pC6v56cwU9dSn9FHYhnck221NOLhyJRK4N0Lf3IlHh200LzDDBzrWk5eaq6WIDZJDTmLZdNbXRorePvF5bjBsXmfstMyjTCX7LRBc6bf2nfSQ0TM4ahRfgZTJIGg2N8q/wauESQy2wMXf5mbbIiXgFKxwQCe22rnU40LW7AaCLSm/wjnNQcy5DqN2tErq7bviXcDjXPYP+Lbafs5PWgmLUAvEP+FFz2w8myARHerzdzR0SExnKwVcwCG9lRO/jOt89yoV1Ye3q7bZYDO+8ryWAmrebvB5saQjHSVMI0cgERQCjPpUx01JlUynHsQiGCeY+srWiaJ4r+AsWpoeiZWyGXaVX7Ut1ILv9L9Wsi33GTyuXjwgxpb4z8y20CCzl5EpE91d2mGU4C3GOOtcVCNP1ON9SPv9xq9lS7fFCIgniPcEmkNij4FEJf96yTZBW68AXsnuB4QiTmhYCzr7H0qEWiugvtGaFXyE2qQ1oQU5VYM5ziuRtLw8GHcqoCtLhUTX0dw4eySq+3h8ZekUhzKOyBO9yO+lQQyRKjDSV20J2XcEw=
  file: target/EdgeConvert-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    repo: BLamy/EdgeConvert
