import React, { Component } from 'react';

import styled from 'styled-components';
import { Collapse, Tabs, Button, Icon } from 'antd';

import 'antd/dist/antd.css';
import './App.css';

import logo from '../public/logo.svg';

const githubUrl = 'https://github.com/BLamy/EdgeConvert';

const PaperCollapse = styled(Collapse)`
  border-radius: 2px;
  margin: 0 auto;
  margin-top: 20px;
  max-width: 800px;
`;

const PaperTabs = styled(Tabs)`
  width: 80%;
  margin: 0 auto;
  max-width: 800px;
  border: none;
`;
const TabsBackground = styled.div`
  border-bottom: 1px solid #d9d9d9;
  background-color: white;
  width: 100%;
  height: 36px;
  position: absolute;
`;

const Paper = styled.div`
  background-color: white;
  border-radius: 2px;
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0,0.08);
  transition: box-shadow 200ms cubic-bezier(0.4, 0.0, 0.2, 1);
`;

const PaperButton = styled(Button)`
  margin-top: 4px;
`;

export default () => (
  <div className="App">
    <div className="App-header">
      <img src={logo} className="App-logo" alt="logo" />
      <h2>Welcome to the EdgeConvert Help</h2>
    </div>
    <TabsBackground />
    <PaperTabs tabBarExtraContent={
      <a href={githubUrl}>
        <PaperButton><Icon type="github" />Fork on Github</PaperButton>
      </a>
    }>
     <Tabs.TabPane tab="Overview" key="1">
       <Paper>
         Hello World
       </Paper>
     </Tabs.TabPane>
     <Tabs.TabPane tab="FAQ" key="2">
       <PaperCollapse bordered={false}>
         <Collapse.Panel header="What is EdgeConvert?" key="1">
           <p>EdgeConvert reads in a file created by Edge Diagrammer and generates the SQL statements necessary to create the tables for a MySQL database.</p>
         </Collapse.Panel>
         <Collapse.Panel header="What is the Edge Diagrammer?" key="2">
           <p>The Edge Diagrammer is a data modeling tool. Edge Diagrammer lets you create diagrams using hundreds of predefined drag-and-drop shapes and arrowheads. Save your own custom diagram templates to establish your own diagramming methods. Edge Diagrammer comes with complete flowcharting templates, network diagramming templates, block diagrams, org charts, and more to get you started.</p>
         </Collapse.Panel>
         <Collapse.Panel header="What is an Edge Diagrammer file?" key="3">
           <p>A file that is generated by the Edge Diagrammer program. The file contains a data model diagram. The file is necessary for the application to generate the SQL statements required to create the tables for a MySQL database. Our upgraded application replaces Edge Diagrammer with other tools and works with other schema description files (e.g. XML) to perform the same functions.</p>
         </Collapse.Panel>
         <Collapse.Panel header="How to convert an .edg file?" key="3">
           <p>Due to recently replacing Edge Diagrammer with other tools and making the application work with other schema description files, you may need to convert Edge Diagrammer files (.edg) to a compatible file type for the application.</p>
        </Collapse.Panel>
       </PaperCollapse>
     </Tabs.TabPane>
     <Tabs.TabPane tab="Download" key="3">
       <Paper>
         Comming Soon...
       </Paper>
     </Tabs.TabPane>
   </PaperTabs>
  </div>
);
